// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABVeGm-zY5x5asuLMuirSgPwNUytnjh4Q',
    appId: '1:581962146656:web:fecd272ded6fbcb0af3405',
    messagingSenderId: '581962146656',
    projectId: 'tintly-by-nikaeva',
    authDomain: 'tintly-by-nikaeva.firebaseapp.com',
    storageBucket: 'tintly-by-nikaeva.firebasestorage.app',
    measurementId: 'G-RYHW9H183S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2BcSZ2zE7iOaHVuya88qIN4wZFasJXrQ',
    appId: '1:581962146656:android:6d6dd3964ed0ec6caf3405',
    messagingSenderId: '581962146656',
    projectId: 'tintly-by-nikaeva',
    storageBucket: 'tintly-by-nikaeva.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8bAwFQDHD-ud7vDyjVMxDt9w_oQdImws',
    appId: '1:581962146656:ios:1cb66ead70a2a057af3405',
    messagingSenderId: '581962146656',
    projectId: 'tintly-by-nikaeva',
    storageBucket: 'tintly-by-nikaeva.firebasestorage.app',
    iosBundleId: 'com.nikaeva.tintly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8bAwFQDHD-ud7vDyjVMxDt9w_oQdImws',
    appId: '1:581962146656:ios:378b0e88a3b7aa45af3405',
    messagingSenderId: '581962146656',
    projectId: 'tintly-by-nikaeva',
    storageBucket: 'tintly-by-nikaeva.firebasestorage.app',
    iosBundleId: 'com.example.tintly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABVeGm-zY5x5asuLMuirSgPwNUytnjh4Q',
    appId: '1:581962146656:web:a32e0491d55662cbaf3405',
    messagingSenderId: '581962146656',
    projectId: 'tintly-by-nikaeva',
    authDomain: 'tintly-by-nikaeva.firebaseapp.com',
    storageBucket: 'tintly-by-nikaeva.firebasestorage.app',
    measurementId: 'G-6TCLW2L4T9',
  );
}
